name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 12 */3 * *'   # cada 3 días
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          curl -X GET "${{ secrets.https://dqesoayspansyrcuynwe.supabase.co }}/rest/v1/${{ secrets.seguidores }}?select=id&limit=1" \
          -H "apikey: ${{ secrets.sb_publishable_7Bd3rMM-muyhMg-yBMR0sQ_JQArVdx7}}" \
          -H "Authorization: Bearer ${{ secrets.sb_publishable_7Bd3rMM-muyhMg-yBMR0sQ_JQArVdx7 }}"